// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDoroaEsYACc-Uz96IQfsZ3KiLKAsCMnY',
    appId: '1:1009777021556:android:dd688935dc0e2a2dae7721',
    messagingSenderId: '1009777021556',
    projectId: 'shoesly-fcb9e',
    storageBucket: 'shoesly-fcb9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPBT_Fu7S9M1EBgro3RgDldtrQymic1q0',
    appId: '1:1009777021556:ios:27fcfe1a3e60ad7aae7721',
    messagingSenderId: '1009777021556',
    projectId: 'shoesly-fcb9e',
    storageBucket: 'shoesly-fcb9e.appspot.com',
    iosBundleId: 'com.example.verygoodcore.shoesly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jkhUbQ4Jr9vtr9hOeXFNxb2MRZ-wHyI',
    appId: '1:1009777021556:web:62ade9916be9f0deae7721',
    messagingSenderId: '1009777021556',
    projectId: 'shoesly-fcb9e',
    authDomain: 'shoesly-fcb9e.firebaseapp.com',
    storageBucket: 'shoesly-fcb9e.appspot.com',
    measurementId: 'G-1LLM6TD09S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPBT_Fu7S9M1EBgro3RgDldtrQymic1q0',
    appId: '1:1009777021556:ios:fed09e8e994a72f1ae7721',
    messagingSenderId: '1009777021556',
    projectId: 'shoesly-fcb9e',
    storageBucket: 'shoesly-fcb9e.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9jkhUbQ4Jr9vtr9hOeXFNxb2MRZ-wHyI',
    appId: '1:1009777021556:web:e7f9c568ed9a5d18ae7721',
    messagingSenderId: '1009777021556',
    projectId: 'shoesly-fcb9e',
    authDomain: 'shoesly-fcb9e.firebaseapp.com',
    storageBucket: 'shoesly-fcb9e.appspot.com',
    measurementId: 'G-G4FT86LPN9',
  );
}
